# Generated by Django 6.0.4 on 2026-04-29 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('prioridad', models.PositiveIntegerField(help_text='Número menor = mayor jerarquía (1 = máxima prioridad)')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['prioridad'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('cant_pasajeros', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True, help_text='False = dado de baja (ej: fue al taller permanente)')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('valido', models.BooleanField(default=False, help_text='True = aprobado por admin, False = pendiente o rechazado')),
                ('rechazado', models.BooleanField(default=False, help_text='True = fue explícitamente rechazado por el admin')),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='reservas.cargo')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=255)),
                ('cant_pasajeros', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField(blank=True, help_text='Opcional: hora estimada de regreso', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, help_text='Se completa automáticamente si el ticket es cancelado por jerarquía')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='reservas.usuario')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='reservas.vehiculo')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-hora_inicio'],
            },
        ),
    ]
