# Generated by Django 6.0.4 on 2026-05-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='nombre',
            field=models.CharField(choices=[('Decano', 'Decano'), ('Secretario', 'Secretario'), ('Usuario', 'Usuario')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='prioridad',
            field=models.PositiveIntegerField(editable=False, help_text='Número menor = mayor jerarquía (1 = máxima prioridad)'),
        ),
    ]
