# Generated by Django 6.0.4 on 2026-05-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_cargo_nombre_alter_cargo_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='prioridad',
            field=models.PositiveIntegerField(help_text='Número menor = mayor jerarquía (1 = máxima prioridad)'),
        ),
    ]
