# Generated by Django 6.0.4 on 2026-06-01 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_cargo_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='nombre',
            field=models.CharField(choices=[('Decano', 'Decano'), ('Secretario', 'Secretario'), ('Usuario', 'Usuario'), ('Administrador SEU', 'Administrador SEU')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='prioridad',
            field=models.PositiveIntegerField(help_text='Número menor = mayor jerarquía (0 = Administrador SEU / Máxima prioridad)'),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('created', 'Creación'), ('cancelled', 'Cancelación'), ('reminder_3_days', 'Recordatorio 3 días'), ('reminder_same_day', 'Recordatorio mismo día')], max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='reservas.ticket')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'indexes': [models.Index(fields=['notification_type', 'sent_at'], name='reservas_no_notific_3c613b_idx')],
            },
        ),
    ]
