# Generated by Django 5.0.7 on 2026-06-02 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_cargo_nombre_alter_cargo_prioridad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacionCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código numérico de 6 dígitos enviado por correo', max_length=6)),
                ('token', models.UUIDField(help_text='Token UUID v4 para el enlace mágico del correo', unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Momento de generación. El registro expira a los 30 minutos.')),
                ('usado', models.BooleanField(default=False, help_text='True = ya verificado. Invalida tanto el código como el token.')),
                ('usuario', models.OneToOneField(help_text='Usuario propietario de esta verificación', on_delete=django.db.models.deletion.CASCADE, related_name='verificacion', to='reservas.usuario')),
            ],
            options={
                'verbose_name': 'Verificación de correo',
                'verbose_name_plural': 'Verificaciones de correo',
            },
        ),
    ]
