# Generated by Django 6.0.4 on 2026-06-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_verificacioncorreo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='exclusivo_decanato',
            field=models.BooleanField(default=False, help_text='True = solo puede ser reservado por el Decano'),
        ),
    ]
