# Generated by Django 6.0.4 on 2026-06-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_vehiculo_exclusivo_decanato'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo_verificado',
            field=models.BooleanField(default=False, help_text='True = el usuario verificó su correo electrónico'),
        ),
    ]
