# Generated by Django 6.0.4 on 2026-06-06 22:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_usuario_correo_verificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecuperacionPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código numérico de 6 dígitos', max_length=6)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token UUID v4 para el enlace de recuperación rápida')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Momento de generación. Expira a los 30 minutos.')),
                ('usado', models.BooleanField(default=False, help_text='True = código/token ya canjeado.')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperaciones_password', to='reservas.usuario')),
            ],
            options={
                'verbose_name': 'Recuperación de contraseña',
                'verbose_name_plural': 'Recuperaciones de contraseña',
            },
        ),
    ]
