# Generated by Django 6.0.4 on 2026-06-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_recuperacionpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='distancia_km',
            field=models.FloatField(default=0.0, help_text='Distancia del viaje calculada desde la universidad al destino'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='latitud_destino',
            field=models.FloatField(blank=True, help_text='Latitud del destino seleccionada en el mapa', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='longitud_destino',
            field=models.FloatField(blank=True, help_text='Longitud del destino seleccionada en el mapa', null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.FloatField(default=0.0, help_text='Kilometraje total recorrido'),
        ),
    ]
