# Generated by Django 6.0.4 on 2026-06-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_ticket_distancia_km_ticket_latitud_destino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='distancia_km',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='latitud_destino',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='longitud_destino',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='kilometraje',
        ),
    ]
