# Generated by Django 6.0.4 on 2026-06-12 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_remove_ticket_distancia_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='conductor',
            field=models.ForeignKey(blank=True, help_text='Chofer asignado al viaje', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_conducidos', to='reservas.usuario'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nombre',
            field=models.CharField(choices=[('Decano', 'Decano'), ('Secretario', 'Secretario'), ('Usuario', 'Usuario'), ('Chofer', 'Chofer'), ('Administrador SEU', 'Administrador SEU')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('cancelado', 'Cancelado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20),
        ),
    ]
