# Generated by Django 6.0.4 on 2026-06-12 22:33

from django.db import migrations

def create_cargo_chofer(apps, schema_editor):
    Cargo = apps.get_model('reservas', 'Cargo')
    if not Cargo.objects.filter(nombre="Chofer").exists():
        Cargo.objects.create(nombre="Chofer", prioridad=4)

def reverse_cargo_chofer(apps, schema_editor):
    Cargo = apps.get_model('reservas', 'Cargo')
    Cargo.objects.filter(nombre="Chofer").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_ticket_conductor_alter_cargo_nombre_and_more'),
    ]

    operations = [
        migrations.RunPython(create_cargo_chofer, reverse_cargo_chofer),
    ]
