# Generated by Django 5.1.5 on 2026-06-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_add_cargo_chofer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='kilometraje',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Distancia en kilómetros desde UTN FRRE al destino', max_digits=10),
        ),
    ]
