# Generated by Django 5.1.5 on 2026-06-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_ticket_kilometraje'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='kilometraje_real',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distancia real recorrida reportada por el chofer al finalizar', max_digits=10, null=True),
        ),
    ]
