# Generated by Django 5.1.5 on 2026-06-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0014_ticket_kilometraje_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='hora_fin_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='hora_inicio_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
