# Generated by Django 6.0.4 on 2026-06-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0015_ticket_hora_fin_real_ticket_hora_inicio_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='distancia_est',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Distancia estimada por el sistema', max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='kilometraje_fin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kilometraje (odómetro) del vehículo al finalizar el viaje', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='kilometraje_inicio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kilometraje (odómetro) del vehículo al comenzar el viaje', max_digits=10, null=True),
        ),
    ]
