# Generated by Django 6.0.4 on 2026-06-17 01:30

from django.db import migrations


def copy_kilometraje_data(apps, schema_editor):
    Ticket = apps.get_model('reservas', 'Ticket')
    for ticket in Ticket.objects.all():
        ticket.distancia_est = ticket.kilometraje
        ticket.kilometraje_fin = ticket.kilometraje_real
        ticket.save()

class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0016_ticket_distancia_est_ticket_kilometraje_fin_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_kilometraje_data),
    ]
