# Generated by Django 6.0.4 on 2026-06-17 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0017_copy_kilometraje_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='kilometraje',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='kilometraje_real',
        ),
    ]
