# Generated by Django 6.0.4 on 2026-06-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0018_remove_ticket_kilometraje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='distancia_real',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distancia real recorrida (calculada automáticamente)', max_digits=10, null=True),
        ),
    ]
