# Generated by Django 6.0.4 on 2026-06-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0019_ticket_distancia_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
