# Generated by Django 5.1.5 on 2026-06-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0020_vehiculo_patente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='para_tercero',
            field=models.BooleanField(default=False, help_text='True = el vehículo será usado por alguien distinto al solicitante'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='requiere_chofer',
            field=models.BooleanField(default=False, help_text='True = la reserva requiere de un chofer'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='requiere_chofer',
            field=models.BooleanField(default=False, help_text='True = es obligatorio que se asigne un chofer para su reserva'),
        ),
    ]
