# Generated by Django 6.0.4 on 2026-06-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0021_ticket_para_tercero_ticket_requiere_chofer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-fecha'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
