# Generated by Django 6.0.4 on 2026-06-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0022_alter_ticket_options_alter_ticket_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(blank=True, choices=[('TUL', 'TUL'), ('TUM', 'TUM'), ('TUP', 'TUP'), ('TOUMRE', 'TOUMRE'), ('IEM', 'IEM'), ('IQ', 'IQ'), ('ISI', 'ISI'), ('LAR', 'LAR')], help_text='Requerido si el cargo es Usuario', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nombre',
            field=models.CharField(choices=[('Decano', 'Decano'), ('Vicedecano', 'Vicedecano'), ('Secretario', 'Secretario'), ('Subsecretario', 'Subsecretario'), ('Usuario', 'Usuario'), ('Chofer', 'Chofer'), ('Administrador SEU', 'Administrador SEU')], max_length=100, unique=True),
        ),
    ]
