# Generated by Django 6.0.4 on 2026-06-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0023_usuario_departamento_alter_cargo_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_anticipacion_reservas', models.PositiveIntegerField(default=3, help_text='Días mínimos de anticipación requeridos para hacer una reserva (usuarios normales)')),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuraciones Globales',
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='distancia_est',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Distancia estimada por el sistema (incluye ida y vuelta, calculada automáticamente x2)', max_digits=10),
        ),
    ]
