# Generated by Django 5.1.5 on 2026-07-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0028_configuracionglobal_minutos_margen'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionglobal',
            name='dias_anticipacion_cancelacion',
            field=models.PositiveIntegerField(default=5, help_text='Días mínimos de anticipación requeridos para cancelar una reserva (usuarios normales)'),
        ),
    ]
