# Generated by Django 5.1.5 on 2026-07-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0029_configuracionglobal_dias_anticipacion_cancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='justificacion_retraso',
            field=models.TextField(blank=True, help_text='Justificación obligatoria si el viaje finaliza más de 2h después de la hora estimada de regreso', null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('created', 'Creación'), ('cancelled', 'Cancelación'), ('reminder_3_days', 'Recordatorio 3 días'), ('reminder_same_day', 'Recordatorio mismo día'), ('reminder_return_late', 'Recordatorio regreso tardío')], max_length=50),
        ),
    ]
