# Generated by Django 5.1.5 on 2026-07-03 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0030_ticket_justificacion_retraso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='inactivo_hasta',
            field=models.DateField(blank=True, help_text='Fecha hasta la que el vehículo estará inactivo por baja temporal (ej: rotura). Null = sin baja temporal activa.', null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('created', 'Creación'), ('cancelled', 'Cancelación'), ('reminder_3_days', 'Recordatorio 3 días'), ('reminder_same_day', 'Recordatorio mismo día'), ('reminder_return_late', 'Recordatorio regreso tardío'), ('vehicle_inactive', 'Baja temporal de vehículo'), ('priority_cancelled', 'Cancelado por prioridad'), ('reassigned', 'Reasignado automáticamente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='activo',
            field=models.BooleanField(default=True, help_text='False = dado de baja permanente (ej: fue al taller o fue descartado)'),
        ),
        migrations.CreateModel(
            name='PermisoReservaExtraordinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('baja_vehiculo', 'Baja temporal de vehículo'), ('prioridad', 'Cancelación por prioridad')], default='baja_vehiculo', help_text='Razón por la que se generó el permiso excepcional.', max_length=20)),
                ('valido_hasta', models.DateField(help_text='Último día en el que el permiso puede usarse (5 días desde la cancelación).')),
                ('usado', models.BooleanField(default=False, help_text='True = el permiso ya fue utilizado para crear una reserva.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ticket_cancelado', models.ForeignKey(help_text='Ticket cancelado que originó este permiso.', on_delete=django.db.models.deletion.CASCADE, related_name='permisos_generados', to='reservas.ticket')),
                ('usuario', models.ForeignKey(help_text='Usuario que puede usar este permiso.', on_delete=django.db.models.deletion.CASCADE, related_name='permisos_emergencia', to='reservas.usuario')),
            ],
            options={
                'verbose_name': 'Permiso de Emergencia',
                'verbose_name_plural': 'Permisos de Emergencia',
                'ordering': ['-creado_en'],
            },
        ),
    ]
