# Generated by Django 5.1.5 on 2026-07-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0031_vehiculo_inactivo_hasta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionglobal',
            name='dias_maximo_anticipacion_reservas',
            field=models.PositiveIntegerField(default=60, help_text='Días máximos de anticipación permitidos para hacer una reserva'),
        ),
        migrations.AlterField(
            model_name='permisoreservaextraordinaria',
            name='valido_hasta',
            field=models.DateField(help_text='Último día en el que el permiso puede usarse (calculado en base a la configuración global).'),
        ),
    ]
