# Generated by Django 5.2.17 on 2026-08-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0032_configuracionglobal_dias_maximo_anticipacion_reservas_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['id_vehiculo', 'estado', 'hora_inicio', 'hora_fin'], name='ticket_conflicto_idx'),
        ),
    ]
