# Generated by Django 5.2.17 on 2026-08-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0033_add_ticket_conflicto_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='recuperacionpassword',
            name='intentos_fallidos',
            field=models.PositiveIntegerField(default=0, help_text='Intentos de código incorrecto. Al llegar a MAX_INTENTOS_CODIGO, el código deja de ser válido aunque no haya expirado por tiempo.'),
        ),
        migrations.CreateModel(
            name='IntentoLoginFallido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(help_text='IP del request que falló al loguearse')),
                ('correo_intentado', models.CharField(blank=True, help_text='Correo con el que se intentó loguear (puede no existir en el sistema)', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Intento de Login Fallido',
                'verbose_name_plural': 'Intentos de Login Fallidos',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['ip', 'creado_en'], name='reservas_in_ip_63500d_idx'), models.Index(fields=['correo_intentado', 'creado_en'], name='reservas_in_correo__084670_idx')],
            },
        ),
    ]
