# Generated by Django 5.2.17 on 2026-08-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0034_rate_limiting'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fin__isnull', True), ('hora_fin__gt', models.F('hora_inicio')), _connector='OR'), name='ticket_hora_fin_posterior_a_hora_inicio'),
        ),
    ]
