# Generated by Django 5.2.17 on 2026-08-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0035_ticket_hora_fin_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificacioncorreo",
            name="intentos_fallidos",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Intentos de código incorrecto. Al llegar a MAX_INTENTOS_CODIGO, el código deja de ser válido aunque no haya expirado por tiempo.",
            ),
        ),
    ]
